name: build

on:
  push:
    branches: [master]
    paths-ignore:
      - LICENSE
      - '*.md'
      - '*.svg'
      - 'examples/**'
      - .editorconfig
      - .gitignore
      - .npmrc
  pull_request:
    branches: [master]
    paths-ignore:
      - LICENSE
      - '*.md'
      - '*.svg'
      - 'examples/**'
      - .editorconfig
      - .gitignore
      - .npmrc

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14, 16]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build library
        run: yarn build

      - name: Run tests
        run: yarn run ci
